title: llc'blog
subtitle: 打字机
description: linux/windows/c++
keywords:
author: John Doe
language: zh-CN
timezone: Asia/Shanghai

url: https://blog.989883.xyz
root: /
permalink: :year/:month/:day/:title/
permalink_defaults:
pretty_urls:
  trailing_index: true
  trailing_html: true

source_dir: source
public_dir: public
tag_dir: tags
archive_dir: archives
category_dir: categories
code_dir: downloads/code
i18n_dir: :lang
skip_render:

new_post_name: :title.md
default_layout: post
titlecase: false
external_link:
  enable: true
  field: site
  exclude: ''
filename_case: 0
render_drafts: false
post_asset_folder: false
relative_link: false
future: true

syntax_highlighter: highlight.js
highlight:
  line_number: true
  auto_detect: false
  tab_replace: ''
  wrap: true
  hljs: false

index_generator:
  path: ''
  per_page: 10
  order_by: -date
per_page: 10
pagination_dir: page

theme: fluid

search:
  path: local-search.xml
  field: post
  content: true
  format: html

deploy:
  type: git
  repo: git@github.com:luchao2424631502/luchao2424631502.github.io.git
  branch: gh-pages
  message: "Site updated: {{ now('YYYY-MM-DD HH:mm:ss') }}"
